### ISSUE TITLE
Establecer la estructura de datos

### ISSUE THREAD

**Issue by EliasMaDeRe** [EliasMaDeRe/PE1#19]
Establecer la forma y estructura que tendrán los datos recolectados. No involucra relaciones o bases de datos.

Tener para: 03/04/2022

**Comment by EliasMaDeRe** [comment]
![123](https://user-images.githubusercontent.com/97937391/161453287-a7d56481-eff5-4372-af63-39bed2a9bf21.PNG)

**Comment by valeeortiz** [comment]
Se repite tecnologías.

**Comment by EliasMaDeRe** [comment]
![Estructuras](https://user-images.githubusercontent.com/97937391/162042230-5a951b33-1343-4dc2-a0d1-771755f896ec.png)
Corregido
