### ISSUE TITLE
Definición para estándar de diseño de interfaces

### ISSUE THREAD

**Issue by CarlosMay7** [EliasMaDeRe/PE1#20]
Crear estándar para el diseño de interfaces

Tener para: 03/04/2022

**Comment by CarlosMay7** [comment]
https://docs.google.com/document/d/1P4Mc5lsS9kj20H3YLfHRntSkBCwzQWbelJBepPZqI0k/edit?usp=sharing

**Comment by EliasMaDeRe** [comment]
Añadir especificación sobre el logo.
