### ISSUE TITLE
Actualizar el Estándar del diseño de interfaces y Mockups (Escalas y Datos de las gráficas)

### ISSUE THREAD

**Issue by valeeortiz** [EliasMaDeRe/PE1#25]

**Comment by valeeortiz** [comment]
Agregar el porcentaje y los casos totales en la parte superior de cada barra de las gráficas

**Comment by JoCaLeFe** [comment]
![image](https://user-images.githubusercontent.com/97575507/161664835-e7ef31c7-0132-4dbc-b6b0-3ca62073941c.png)
![image](https://user-images.githubusercontent.com/97575507/161664652-4bc598da-260d-4740-a0d1-8611923adf56.png)
![image](https://user-images.githubusercontent.com/97575507/161664682-3af5a157-346f-45d5-9e5d-de2c6c415e11.png)

**Comment by EliasMaDeRe** [comment]
Gráfica 2
1.-Leyenda vertical en la gráfica
2.-Quitar botón de 1 mes
3.-Leyenda en la parte superior corregir de 6 meses a " en el último mes ".
4,-Leyenda que mencione el total de ofertas revisadas.

**Comment by JoCaLeFe** [comment]
Corrección Gráfica 2:
![image](https://user-images.githubusercontent.com/97575507/161866798-a44e25e4-793a-4f7d-96a9-cc3b6696407f.png)

**Comment by CarlosMay7** [comment]
> Corrección Gráfica 2: ![image](https://user-images.githubusercontent.com/97575507/161866798-a44e25e4-793a-4f7d-96a9-cc3b6696407f.png)

Aquí habría que cambiar el total de ofertas consultadas hacia arriba a la derecha

**Comment by EliasMaDeRe** [comment]
Gráfica 3:
1.-Leyenda en la parte superior de la gráfica que menciona representa los filtros seleccionados por el usuario.
2.-Añadir leyenda vertical y horizontal de la gráfica.
3.-Agregar valor de la gráfica sobre esta.
4.-Añadir leyenda de las ofertas totales consultadas en la parte según el estándar de interfaz.

**Comment by valeeortiz** [comment]
Corrección Gráfica 2:
![grafica2](https://user-images.githubusercontent.com/97641033/162069042-9ca8f614-f626-4430-8425-d1e55dc6d46e.jpeg)

**Comment by valeeortiz** [comment]
Corrección gráfica 3:
![WhatsApp Image 2022-04-06 at 3 52 47 PM](https://user-images.githubusercontent.com/97641033/162069157-fa21e71c-da18-426d-8c0c-6dee90f576b7.jpeg)
