### ISSUE TITLE
Definición del diccionario (Palabras Clave)

### ISSUE THREAD

**Issue by FernandoJoachin** [EliasMaDeRe/PE1#26]
Establecer las palabras claves del diccionario  que el sistema usará para recolectar la información a partir de ese punto en las ofertas. Lo anterior debe ser documentado en un archivo por separado.

El documento también debe describir el proceso que se le realizará a los datos recolectados con este diccionario.

**Comment by FernandoJoachin** [comment]
# Definición del diccionario
El diccionario de las palabras claves será estático, donde de manera manual se revisará la recolección de la información. Esto último con el propósito de seleccionar solamente la información que realmente necesitamos.
## Tecnologías solicitadas
Las palabras claves para recolectar las tecnologías solicitadas serán:

1.  Conocimientos 
2. Knowledge 
3.  Experiencia 
4. Experience
5.  Habilidades 
6. Skills   
7.  Herramientas 
8. Tools
9.  Requisitos ´
10. Requirements

## Categorías de información
Las palabras claves para recolectar las categorías de información serán:

1.   **Tamaño de empresa**
     1. Tamaño

**Comment by EliasMaDeRe** [comment]
> # Definición del diccionario
> El diccionario de las palabras claves será estático, donde de manera manual se revisará la recolección de la información. Esto último con el propósito de seleccionar solamente la información que realmente necesitamos.
> 
> ## Tecnologías solicitadas
> Las palabras claves para recolectar las tecnologías solicitadas serán:
> 
> 1. Conocimientos (Knowledge)
> 2. Experiencia (Experience)
> 3. Habilidades (Skills)
> 4. Herramientas (Tools)
> 5. Requisitos (Requirements)
> 
> ## Categorías de información
> Las palabras claves para recolectar las categorías de información serán:
> 
> 1. **Salario**
>    
>    1. Salario
>    2. Sueldo
> 2. **Locación**
>    
>    1. Aguascalientes
>    2. Baja California
>    3. Baja California Sur
>    4. Campeche
>    5. Chiapas
>    6. Chihuahua
>    7. Coahuila
>    8. Colima
>    9. CDMX/México
>    10. Durango
>    11. Estado de México
>    12. Guanajuato
>    13. Guerrero
>    14. Hidalgo
>    15. Jalisco
>    16. Michoacán
>    17. Morelos
>    18. Nayarit
>    19. Nueva León
>    20. Oaxaca
>    21. Puebla
>    22. Querétaro
>    23. Quintana Roo
>    24. San Luis Potosí
>    25. Sinaloa
>    26. Sonora
>    27. Tabasco
>    28. Tamaulipas
>    29. Tlaxcala
>    30. Veracruz
>    31. Yucatán
>    32. Zacatecas
> 3. **Modalidad**
>    
>    1. Trabajar desde casa
>    2. Work Remotely
>    3. Remoto
> 4. **Tamaño de empresa**
>    
>    1. Tamaño

Las palabras del diccionario son solo para las tecnologías solicitadas @FernandoJoachin ya que el diccionario proporciona una señal para que el sistema recolecte las palabras y se contabilicen posteriormente
