### ISSUE TITLE
Actualizar Requerimiento Presentador de Gráficas, apartado Tecnologías de Solicitadas (Escalas y Datos de las gráficas)

### ISSUE THREAD

**Issue by EliasMaDeRe** [EliasMaDeRe/PE1#27]
El requerimiento "Presentador de Gráficas" debe especificar que durante la presentación de la gráfica de Tecnologías Solicitadas, mostrará el total de ofertas revisadas, así como el valor neto de las repeticiones de cada tecnología arriba de su gráfica.

**Comment by valeeortiz** [comment]
¿Se tendría que agregar otro apartado especificando lo mismo para la gráfica del sueldo con las categorías? Por ejemplo "El sistema al presentar la gráfica de las categorías de información mostrará el sueldo anual en la parte superior de su gráfica"

**Comment by EliasMaDeRe** [comment]
> ¿Se tendría que agregar otro apartado especificando lo mismo para la gráfica del sueldo con las categorías? Por ejemplo "El sistema al presentar la gráfica de las categorías de información mostrará el sueldo anual en la parte superior de su gráfica"

Solo las tecnologías solicitadas.
