### ISSUE TITLE
Encontrar herramienta de estándar de codificación (python)

### ISSUE THREAD

**Issue by EliasMaDeRe** [EliasMaDeRe/PE1#32]

**Comment by EliasMaDeRe** [comment]
Nota: Tratar de encontrar que sea compatible con VisualStudio Code y potencialmente Spyder

**Comment by FernandoJoachin** [comment]
Link del video para descargar el estandar de codificación
https://www.youtube.com/watch?v=7llJdfKfccE

**Comment by FernandoJoachin** [comment]
> Link del video para descargar el estandar de codificación https://www.youtube.com/watch?v=7llJdfKfccE

Es necesario cambiar el estandar de codificación que habiamos hecho anteriormente. Hay que actualizarlo con respecto a este manual de estandar de codificación de Python https://recursospython.com/pep8es.pdf

**Comment by EliasMaDeRe** [comment]
Actualizar definicion del estandar para que concuerde con la herramienta.

**Comment by FernandoJoachin** [comment]
## Nombrado de variables
Las variables deben ir en minúscula, con las palabras separadas por un guión bajo, aplicándose éstos tanto como sea necesario para mejorar la legibilidad.
 - usuario = "John"
 -  lista_nombre = ["John", "Hans", "Anna"]

Las nombres de constantes  deberán ir escritas con todas las letras en mayúscula y con guiones bajos separando
palabras. 
- MAX_OVERFLOW 
-  TOTAL

## Nombrado de archivos
Los archivos deben tener un nombre corto y en minúscula. Guiones bajos pueden utilizarse si mejora la legiblidad.
 - nombre_de_archivo_largo.python

## Nombrado de funciones
Las funciones deben ser en minúscula, con las palabras separadas por un guión bajo, aplicándose éstos tanto como sea necesario para mejorar la legibilidad.

 - def  nombre_funcion_largo():
 
## Nombrado de clases
Los nombres de clases deben utilizar la convención “CapWords” (palabras que comienzan con mayúsculas).
-class NombradoClase:

## Diseño del código
Usa 4 (cuatro) espacios por indentación.
Limita todas las líneas a un máximo de 79 caracteres.
Las importaciones deben estar en líneas separadas, por ejemplo:
-import os
-import sys
Siempre rodea estos operadores binarios con un espacio en cada lado: asignación (=), asignación de aumentación (+=, -=, etc.), comparaciones (==, <, >, !=, <>, <=, >=, in, not in, is, is not), “Booleans” (and, or, not). Por ejemplo:
-i = i + 1
-submitted += 1
-x = x*2 - 1
-hypot2 = x*x + y*y
-c = (a+b) * (a-b)

## Comentarios
Los comentarios deben ser oraciones completas. Si un comentario es una frase u oración, su primera palabra debe comenzar con mayúscula, a menos que sea un identificador que comienza con minúscula.

Los comentarios en bloque están indentados al mismo nivel que ese código. Cada línea de un comentario en bloque comienza con un # (numeral) y un espacio (a menos que esté indentado dentro del mismo comentario). Los párrafos dentro de un comentario en bloque están separados por una línea que contiene únicamente un # (numeral).

Los comentarios en línea deberían estar separados por al menos dos espacios de la sentencia. Deberían empezar con un # (numeral) seguido de un espacio. Solamente en casos especificos.
