### ISSUE TITLE
Editar video de segunda entrega Avance del Proyecto Final

### ISSUE THREAD

**Issue by EliasMaDeRe** [EliasMaDeRe/PE1#33]

**Comment by JoCaLeFe** [comment]
https://alumnosuady-my.sharepoint.com/:f:/g/personal/a21216389_alumnos_uady_mx/EqyRxBxnzblDpxVscjFNvPUBH5_OAHtLOAi4DzVdeLvCwA?e=JSMygR

**Comment by JoCaLeFe** [comment]
Actualización: https://alumnosuady-my.sharepoint.com/:v:/g/personal/a21216389_alumnos_uady_mx/EQvD40iHamhIkwHakOGSxhQBaeLMHNf6iVy5q_UVpQ07iA?e=MmC7ae
