### ISSUE TITLE
Filtrar "Locacion" en DF

### ISSUE THREAD

**Issue by EliasMaDeRe** [EliasMaDeRe/PE1#36]

**Comment by valeeortiz** [comment]
Código de depuración de Locación

import pandas as pd
df = pd.read_csv('glassdoor_jobs.csv')

#depurar locacion

df = df.dropna()
df = df[df['Location'] != 'Trabajo desde casa']
locacion = df['Location'].str.replace("é", "e")
df['Locacion'] = locacion
df.to_csv('Locacion.csv', index = False)

**Comment by valeeortiz** [comment]
Código de depuración de Locación CORREGIDO
#depurar locacion

df = df.dropna()
df = df[df['Location'] != 'Trabajo desde casa']
locacion = df['Location']
df['Locacion'] = locacion
df.to_csv('Locacion.csv', index = False)
