### ISSUE TITLE
Filtrar "Tamaño de empresa" en DF

### ISSUE THREAD

**Issue by EliasMaDeRe** [EliasMaDeRe/PE1#37]

**Comment by JoCaLeFe** [comment]
Código Primera Parte Depuración Tamaño de Empresa:

#depurar Size

df = df[df['Size'] != '-1']
df = df[df['Size'] != 'No se sabe']

size = df['Size'].apply(lambda x: x.split('e')[1])
size = size.apply(lambda x: x.replace(' ', '').replace('a', '-'))
sizeMin = size.apply(lambda x: int(x.split('-')[0]) if '-' in x else int(x))
sizeMax = size.apply(lambda x: int(x.split('-')[1]) if '-' in x else int(x))

df['Tamaño Empresa'] = sizeMax
df.to_csv('tamañoEmpresa.csv', index = False)

**Comment by FernandoJoachin** [comment]
> 

#depurar Size

df = df[df['Size'] != '-1']
df = df[df['Size'] != 'No se sabe']

size = df['Size'].apply(lambda x: x.split('e')[1])
size = size.apply(lambda x: x.replace(' ', '').replace('a', '-'))
sizeMin = size.apply(lambda x: int(x.split('-')[0]) if '-' in x else int(x))
sizeMax = size.apply(lambda x: int(x.split('-')[1]) if '-' in x else int(x))
sizenew= sizeMax.replace([50,200,500],0).replace([1000,5000],1).replace(10000,2)
sizecontar =  sizenew.value_counts()

df['Tamaño Empresa'] = sizeMax
df.to_csv('tamañoEmpresa.csv', index = False)
