### ISSUE TITLE
Filtrar "Fecha" en DF

### ISSUE THREAD

**Issue by EliasMaDeRe** [EliasMaDeRe/PE1#38]

**Comment by CarlosMay7** [comment]
Código de depuración de fechas

#depurar fechas
df = df.dropna()
fecha = df['Fecha'].apply(lambda x: x.split('d')[0])
fecha= fecha.apply(lambda x: x.replace('24 horas', '1').replace(' ',''))
fecha= fecha.apply(lambda x: int(x))
df['Fecha'] = fecha
df.to_csv('fecha.csv', index = False)
`
