### ISSUE TITLE
Actualizar requerimiento de Locación

### ISSUE THREAD

**Issue by EliasMaDeRe** [EliasMaDeRe/PE1#39]
Ya no se filtrará por estado de México, si no por locación disponible en el dataframe.

**Comment by FernandoJoachin** [comment]
Se realizarón los cambios pertineneces en el documentos de requerimientos: https://docs.google.com/document/d/1IAMohTxGzd-YOU6YF075SvpOvf7_YdzP/edit?usp=sharing&ouid=113066813380021140710&rtpof=true&sd=true
