### ISSUE TITLE
Limpiar Modalidad (Presencial o Virtual)

### ISSUE THREAD

**Issue by EliasMaDeRe** [EliasMaDeRe/PE1#41]
Miercoles

**Comment by valeeortiz** [comment]
#depurar modalidad

df = df.dropna()
df = df[df['Location'] != -1]
modalidad_virtual = df['Location'].apply(lambda x: x.replace('Trabajo desde casa', '0'))
modalidad_presencial = modalidad_virtual.apply(lambda x: x != '0').replace(str('Location'), '1')
modalidad = modalidad_presencial.replace(True, 'Presencial').replace(False, 'Virtual')
df['Modalidad'] = modalidad
df.to_csv('Modalidad.csv', index = False)

**Comment by valeeortiz** [comment]
#depurar modalidad

df = df.dropna()
df = df[df['Location'] != -1]
modalidad_virtual = df['Location'].apply(lambda x: x.replace('Trabajo desde casa', '0'))
modalidad_presencial = modalidad_virtual.apply(lambda x: x != '0')
modalidad = modalidad_presencial.replace(True, 'Presencial').replace(False, 'Virtual')
df['Modalidad'] = modalidad
df.to_csv('Modalidad.csv', index = False)
