### ISSUE TITLE
Limpiar Descripcion con el Diccionario establecido

### ISSUE THREAD

**Issue by EliasMaDeRe** [EliasMaDeRe/PE1#42]
Miercoles

**Comment by EliasMaDeRe** [comment]
https://www.geeksforgeeks.org/python-extract-words-from-given-string/

**Comment by FernandoJoachin** [comment]
import pandas as pd

df = pd.read_csv('glassdoor_jobs.csv')

tecno = df ["Job Description"].apply(lambda x: x.split("knowledge",1)[1] if "knowledge" in x else( x.split("Knowledge",1)[1] if "Knowledge" in x else( x.split("KNOWLEDGE",1)[1] if "KNOWLEDGE" in x else (x.split("experience",1)[1] if "experience" in x else(x.split("Experience",1)[1] if "Experience" in x else(x.split("EXPERIENCE",1)[1] if "EXPERIENCE" in x else (x.split("skills",1)[1] if "skills" in x else(x.split("Skills",1)[1] if "Skills" in x else(x.split("SKILLS",1)[1] if "SKILLS" in x else (x.split("tools",1)[1] if "tools" in x else(x.split("Tools",1)[1] if "Tools" in x else(x.split("TOOLTS",1)[1] if "TOOLS" in x else (x.split("requirements",1)[1] if "requirements" in x else(x.split("Requirements",1)[1] if "Requirements" in x else(x.split("REQUERIMENTS",1)[1] if "REQUERIMENTS" in x else False)))))))))))))))

df ["Job Description"] = tecno
df = df[df['Job Description'] != False]

**Comment by FernandoJoachin** [comment]
import pandas as pd

df = pd.read_csv('glassdoor_jobs.csv')

tecno = df ["Job Description"].apply(lambda x: x.split("knowledge",1)[1] if "knowledge" in x else( x.split("Knowledge",1)[1] if "Knowledge" in x else( x.split("KNOWLEDGE",1)[1] if "KNOWLEDGE" in x else (x.split("experience",1)[1] if "experience" in x else(x.split("Experience",1)[1] if "Experience" in x else(x.split("EXPERIENCE",1)[1] if "EXPERIENCE" in x else (x.split("skills",1)[1] if "skills" in x else(x.split("Skills",1)[1] if "Skills" in x else(x.split("SKILLS",1)[1] if "SKILLS" in x else (x.split("tools",1)[1] if "tools" in x else(x.split("Tools",1)[1] if "Tools" in x else(x.split("TOOLTS",1)[1] if "TOOLS" in x else (x.split("requirements",1)[1] if "requirements" in x else(x.split("Requirements",1)[1] if "Requirements" in x else(x.split("REQUERIMENTS",1)[1] if "REQUERIMENTS" in x else False)))))))))))))))

df ["Job Description"] = tecno
df = df[df['Job Description'] != False]

tecno_palabras = df["Job Description"].str.split()

**Comment by FernandoJoachin** [comment]
import pandas as pd
import re

df = pd.read_csv('glassdoor_jobs.csv')

tecno = df ["Job Description"].apply(lambda x: x.split("knowledge",1)[1] if "knowledge" in x else( x.split("Knowledge",1)[1] if "Knowledge" in x else( x.split("KNOWLEDGE",1)[1] if "KNOWLEDGE" in x else (x.split("experience",1)[1] if "experience" in x else(x.split("Experience",1)[1] if "Experience" in x else(x.split("EXPERIENCE",1)[1] if "EXPERIENCE" in x else (x.split("skills",1)[1] if "skills" in x else(x.split("Skills",1)[1] if "Skills" in x else(x.split("SKILLS",1)[1] if "SKILLS" in x else (x.split("tools",1)[1] if "tools" in x else(x.split("Tools",1)[1] if "Tools" in x else(x.split("TOOLTS",1)[1] if "TOOLS" in x else (x.split("requirements",1)[1] if "requirements" in x else(x.split("Requirements",1)[1] if "Requirements" in x else(x.split("REQUERIMENTS",1)[1] if "REQUERIMENTS" in x else "NaD")))))))))))))))

df ["Job Description"] = tecno

for i in range (df["Job Description"].shape[0]):
    if (df["Job Description"].loc[i]) != "NaD":
        if (df["Job Description"].index[i]) == 0:
            res = re.findall(r'\w+', df["Job Description"].loc[i] )
            df1 = pd.DataFrame(res)
            frames = [df1]
        else:
            res = re.findall(r'\w+', df["Job Description"].loc[i] )
            df1 = pd.DataFrame(res)
            frames.append(df1)

result = pd.concat(frames)
result_f = result.value_counts()

**Comment by FernandoJoachin** [comment]
```
import pandas as pd
import re

df = pd.read_csv('glassdoor_jobs.csv')

tecno = df["Job Description"].apply(lambda x: x.split("knowledge",1)[1] if "knowledge" in x else( x.split("Knowledge",1)[1] if "Knowledge" in x else( x.split("KNOWLEDGE",1)[1] if "KNOWLEDGE" in x else (x.split("experience",1)[1] if "experience" in x else(x.split("Experience",1)[1] if "Experience" in x else(x.split("EXPERIENCE",1)[1] if "EXPERIENCE" in x else (x.split("skills",1)[1] if "skills" in x else(x.split("Skills",1)[1] if "Skills" in x else(x.split("SKILLS",1)[1] if "SKILLS" in x else (x.split("tools",1)[1] if "tools" in x else(x.split("Tools",1)[1] if "Tools" in x else(x.split("TOOLTS",1)[1] if "TOOLS" in x else (x.split("requirements",1)[1] if "requirements" in x else(x.split("Requirements",1)[1] if "Requirements" in x else(x.split("REQUERIMENTS",1)[1] if "REQUERIMENTS" in x else "NaD")))))))))))))))

df["Job Description"] = tecno

contador = 0
for i in range (df["Job Description"].shape[0]):
    if (df["Job Description"].loc[i]) != "NaD":
        if contador == 0:
            res = re.findall(r'\w+', df["Job Description"].loc[i] )
            df1 = pd.DataFrame(res)
            frames = [df1]
            contador += 1
        else:
            res = re.findall(r'\w+', df["Job Description"].loc[i] )
            df1 = pd.DataFrame(res)
            frames.append(df1)

result = pd.concat(frames)
result_f = result.value_counts()
```

**Comment by FernandoJoachin** [comment]
```
import pandas as pd
import re

df = pd.read_csv('glassdoor_jobs.csv')

tecno = df["Job Description"].apply(lambda x: x.split("knowledge",1)[1] if "knowledge" in x else( x.split("Knowledge",1)[1] if "Knowledge" in x else( x.split("KNOWLEDGE",1)[1] if "KNOWLEDGE" in x else (x.split("experience",1)[1] if "experience" in x else(x.split("Experience",1)[1] if "Experience" in x else(x.split("EXPERIENCE",1)[1] if "EXPERIENCE" in x else (x.split("skills",1)[1] if "skills" in x else(x.split("Skills",1)[1] if "Skills" in x else(x.split("SKILLS",1)[1] if "SKILLS" in x else (x.split("tools",1)[1] if "tools" in x else(x.split("Tools",1)[1] if "Tools" in x else(x.split("TOOLTS",1)[1] if "TOOLS" in x else (x.split("requirements",1)[1] if "requirements" in x else(x.split("Requirements",1)[1] if "Requirements" in x else(x.split("REQUERIMENTS",1)[1] if "REQUERIMENTS" in x else "NaD")))))))))))))))

df["Job Description"] = tecno
contador = 0
for i in range (df["Job Description"].shape[0]):
    if (df["Job Description"].loc[i]) != "NaD":
        if contador == 0:
            res = re.findall(r'\w+', df["Job Description"].loc[i] )
            df1 = pd.DataFrame(res)
            frames = [df1]
            contador += 1
        else:
            res = re.findall(r'\w+', df["Job Description"].loc[i] )
            df1 = pd.DataFrame(res)
            frames.append(df1)

result = pd.concat(frames)
result_f = result.value_counts()

result_f = pd.DataFrame(result_f)
result_f = result_f.rename(columns={0:'Repeticiones'})
result_f = result_f.reset_index()
result_f = result_f.rename(columns={0:'Palabras'})



with open("mi_archivo.txt") as file_object:
    lines = file_object.readlines()
    lines = list(map(lambda x: x.rstrip('\n'),lines))
lines = pd.DataFrame(lines)
lines = lines.rename(columns={0:'Tecnologias'})


contador2 = 0
for line in range (lines['Tecnologias'].shape[0]):
    for j in range (result_f["Palabras"].shape[0]):
        if (result_f.loc[j,'Palabras']) == lines.loc[line,'Tecnologias']:
            if contador2 == 0:
                lista_frec = [result_f.loc[j,'Repeticiones']]
                lista_tecno = [result_f.loc[j,'Palabras']]
                contador2 += 1
            else:
                lista_frec.append(result_f.loc[j,'Repeticiones'])
                lista_tecno.append(result_f.loc[j,'Palabras'])
            
               
            
df_t = pd.DataFrame()
df_t['Tecnologia'] = None
df_t['Frecuencia'] = None
df_t['Tecnologia'] = lista_tecno
df_t['Frecuencia'] = lista_frec
```
