### ISSUE TITLE
Ver interfaz, recibir informacion boton

### ISSUE THREAD

**Issue by EliasMaDeRe** [EliasMaDeRe/PE1#44]
Miercoles

**Comment by CarlosMay7** [comment]
from tkinter import *
from PIL import ImageTk, Image


#Creando la ventana en donde estará el programa
ventana = Tk()

ventana.title("Link Job")
ventana.geometry("800x400")
ventana.config(bg="ghost white")

#Crear imagen del logo

logo = Image.open("Logo.png")
logo = logo.resize((900,75), Image.ANTIALIAS)

log = ImageTk.PhotoImage(logo)
mostrarlogo = Label(ventana, image = log)
mostrarlogo.config(bg = "sandy brown")
mostrarlogo.place(relx=1, rely=0, relwidth=1, anchor='ne')

#Definir imagenes de gráficas

tecnologias = Image.open("Mockup de la gráfica de barras sobre las tecnologías.png")
tecnologias = tecnologias.resize((1000,290), Image.ANTIALIAS)

tec = ImageTk.PhotoImage(tecnologias)
mostrartec = Label(ventana, image = tec)
mostrartec.config(bg = "ghost white")
mostrartec.place(relx=1, rely=0.1, relwidth=1,anchor='ne')

genesp = Image.open("Mockup de la gráfica de barras sobre los filtros generales y específicos.png")
genesp = genesp.resize((1000,290), Image.ANTIALIAS)

genespes = ImageTk.PhotoImage(genesp)
mostrargenesp = Label(ventana, image = genespes)
mostrargenesp.config(bg = "ghost white")
mostrargenesp.place(relx=1, rely=0.52, relwidth=1,anchor='ne')


#Las opciones que tendrá el dropdown general
opcionesgen=[ "Modalidad", "Salario", "Locación", "Tamaño de empresa"]

#Las opciones que tendrá el dropdown general
opcionesesp=[ "Presencial", "Virtual", "Locaciones, Empresa grande, Empresa Mediana, Empresa Pequeña, "]


#Creando los dropdowns

#Aquí se pone lo que va a aparecer primero en los botones
clickgen = StringVar()
clickgen.set( "Elige el filtro general" )
clickesp = StringVar()
clickesp.set( "Elige el filtro específico" )

#Aquí se crean, el OptionsMenu es para decir que es un menú de opciones, en los paréntesis primero aparece en donde está ubicado, la oración que tendra por default y las opciones que contendrá la lista y lo que hará con las opciones seleccionadas

dropdowngen = OptionMenu( ventana , clickgen, *opcionesgen)
dropdowngen.config(bg="sandy brown")
dropdowngen.place(relx=0.4, rely=0.95, relwidth=0.3,anchor='ne')

dropdownesp = OptionMenu( ventana , clickesp, *opcionesesp)
dropdownesp.config(bg="sandy brown")
dropdownesp.place(relx=0.8, rely=0.95, relwidth=0.3,anchor='ne')
   
ventana.mainloop()
